### ISSUE TITLE
Error when player runs `/verify` command

### ISSUE THREAD

**Issue by Blitheness** [TheShireMinecraft/minecraft-player-verification#19]
```log
[01:36:24 INFO]: ************* issued server command: /verify
[01:36:24 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'verify' in plugin PlayerVerification v1.0.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: io/jsonwebtoken/Jwts
        at us.shirecraft.verification.services.TokenService.generateTokenForUuid(TokenService.java:21) ~[minecraft-player-verification-1.0.0.jar:?]
        at us.shirecraft.verification.commands.VerifyCommand.buildVerificationUrlForPlayer(VerifyCommand.java:44) ~[minecraft-player-verification-1.0.0.jar:?]
        at us.shirecraft.verification.commands.VerifyCommand.onCommand(VerifyCommand.java:37) ~[minecraft-player-verification-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 17 more
Caused by: java.lang.ClassNotFoundException: io.jsonwebtoken.Jwts
        at us.shirecraft.verification.services.TokenService.generateTokenForUuid(TokenService.java:21) ~[minecraft-player-verification-1.0.0.jar:?]
        at us.shirecraft.verification.commands.VerifyCommand.buildVerificationUrlForPlayer(VerifyCommand.java:44) ~[minecraft-player-verification-1.0.0.jar:?]
        at us.shirecraft.verification.commands.VerifyCommand.onCommand(VerifyCommand.java:37) ~[minecraft-player-verification-1.0.0.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 17 more
```

**Comment by Blitheness** [comment]
Maven shade plugin is missing

**Comment by Blitheness** [comment]
Latest problem:

```log
[23:49:36 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'verify' in plugin PlayerVerification v1.0.0-SNAPSHOT
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:155) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:909) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCommand(ServerGamePacketListenerImpl.java:2382) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$18(ServerGamePacketListenerImpl.java:2153) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1359) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:183) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1336) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1329) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1307) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[paper-1.19.jar:git-Paper-81]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:303) ~[paper-1.19.jar:git-Paper-81]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: io.jsonwebtoken.lang.UnknownClassException: Unable to load class named [io.jsonwebtoken.impl.DefaultJwtBuilder] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.  Have you remembered to include the jjwt-impl.jar in your runtime classpath?
        at io.jsonwebtoken.lang.Classes.forName(Classes.java:93) ~[MinecraftPlayerVerification.jar:?]
        at io.jsonwebtoken.lang.Classes.newInstance(Classes.java:137) ~[MinecraftPlayerVerification.jar:?]
        at io.jsonwebtoken.Jwts.builder(Jwts.java:144) ~[MinecraftPlayerVerification.jar:?]
        at us.shirecraft.verification.services.TokenService.generateTokenForUuid(TokenService.java:21) ~[MinecraftPlayerVerification.jar:?]
        at us.shirecraft.verification.commands.VerifyCommand.buildVerificationUrlForPlayer(VerifyCommand.java:44) ~[MinecraftPlayerVerification.jar:?]
        at us.shirecraft.verification.commands.VerifyCommand.onCommand(VerifyCommand.java:37) ~[MinecraftPlayerVerification.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[paper-api-1.19-R0.1-SNAPSHOT.jar:?]
        ... 17 more
```
